### ISSUE TITLE
Ignore templating code

### ISSUE THREAD

**Issue by joris974** [zacechola/grunt-bootlint#43]
```html
<div class="row">
  <div class="col-xs-11"></div>
  <% if (condition) { %>
    <div class="col-xs-1"></div>
  <% } %>
</div>
```
This code raises errors E013 and E014 and I don't want to relax those errors on the entire project.
Is it possible to have bootlint ignore templating code?

**Comment by cvrebert** [comment]
Nope. See https://github.com/twbs/bootlint/issues/183
Lint your final rendered HTML instead.
